"""rename department

Revision ID: 056bc345d2e7
Revises: e4c9fd459c64
Create Date: 2024-04-11 13:11:49.970887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056bc345d2e7'
down_revision = 'e4c9fd459c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
